name: Build and Push Docker Image

#Trigger for the workflow is defined here
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest  # specifies that the job will run on the latest version of the Ubuntu runner provided by GitHub Actions.

    steps:
    - name: Get current date and time
      run: |
        DATE=$(date +'%Y%m%d%H%M%S')
        echo "DATE=$DATE" >> $GITHUB_ENV
    - name: Checkout repository   # descriptive name for action
      uses: actions/checkout@v2   # "actions/checkout" action is a predefined action provided by GitHub

    - name: Set up Docker Buildx              # descriptive name for action
      uses: docker/setup-buildx-action@v2     # using a predefined action provided by GitHub

    - name: Log in to Docker Hub              # descriptive name for action
      uses: docker/login-action@v2            # using a predefined action provided by GitHub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}    # using credentials stored in GitHub secrets for loging in to dockerhub
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image       # descriptive name for action
      uses: docker/build-push-action@v3       # using a predefined action provided by GitHub
      with:
        context: .
        push: true
        tags: |
          just4danish/qr-controller-zaair:T${{ env.DATE }}
          just4danish/qr-controller-zaair:latest